# @package _global_
defaults:
  - _self_

dataset_type: NuScenesDataset
dataset_root: data/nuscenes
gt_paste_stop_epoch: -1
reduce_beams: 32
load_dim: 5
use_dim: 5
load_augmented: null

point_cloud_range: [-54.0, -54.0, -5.0, 54.0, 54.0, 3.0]
voxel_size: [0.075, 0.075, 0.2]
image_size: [256, 704]

augment2d:
  resize: [[0.38, 0.55], [0.48, 0.48]]
  rotate: [-5.4, 5.4]
  gridmask:
    prob: 0.0
    fixed_prob: true

augment3d:
  scale: [0.9, 1.1]
  rotate: [-0.78539816, 0.78539816]
  translate: 0.5

object_classes:
  - car
  - truck
  - construction_vehicle
  - bus
  - trailer
  - barrier
  - motorcycle
  - bicycle
  - pedestrian
  - traffic_cone

map_classes:
  - drivable_area
  - ped_crossing
  - walkway
  - stop_line
  - carpark_area
  - divider
