# @package _global_
defaults:
  - _self_

model:
  encoders:
    camera:
      vtransform:
        in_channels: 256
        out_channels: 80
        image_size: ${image_size}
        feature_size: [32, 88]
        zbound: [-10.0, 10.0, 20.0]
        dbound: [1.0, 60.0, 0.5]
        downsample: 2
